### ISSUE TITLE
Migrate to PHP v7.4

### ISSUE THREAD

**Issue by ghost** [ppshobi/psonic#13]
I moved to new version of PHP (v.7.4) and the library is failing with the changes of the new api. In particular in line `psonic/src/Commands/Command.php#20`. This is due to the recent change in the `implode()` method, so now the arguments are backwards.

The only change to apply in this case is the code `return $this->command . " " . implode($this->parameters, " ") . "\n";` move it to `return $this->command . " " . implode(" ", $this->parameters) . "\n";`

That should solve the issue while the library is being adapted to new version. Could you post a new release with this fix?

**Comment by ppshobi** [comment]
Thanks for the comment. I've made the changes and added php7.4 to the Travis file to test against. `v1.2.0` will hopefully help you. Thanks
