### ISSUE TITLE
Server response is not complete

### ISSUE THREAD

**Issue by smoothsea** [ppshobi/psonic#22]
When I set a big query limitation，I found the result of the response is not complete.
I check the code:
```
./Client.php:
56: $message = stream_get_line($this->resource, 2048, "\r\n");
```

**Comment by ppshobi** [comment]
Yes, I believe we need to read until there is empty read is occurred. But mostly 2mb worth of suggestions will help you reach a long way. But could you try to send a PR patching this issue? I can review it and merge quickly? Currently I am super packed with work.

**Comment by smoothsea** [comment]
Okay, I will try. Thanks for your reply.

**Comment by n0099** [comment]
#23
