### ISSUE TITLE
Password set on Ingest/Control connect()

### ISSUE THREAD

**Issue by ghost** [ppshobi/psonic#7]
I am trying to set a custom password different from the default one 'SecretPassword', however, everytime the connection fails with 'fwrite' error. 

Is it really possible to set that password?

**Comment by ppshobi** [comment]
It should be possible. If not the password is pointless. Seems like a bug
to me. Let me update you soon.

**Comment by ghost** [comment]
Sure, can I help you during the process?

**Comment by ppshobi** [comment]
There was indeed a bug, Thanks for pointing out, I have merged the changes to master. Will release a version ASAP. 
If you would like to check out the bug, this was the issue 

https://github.com/ppshobi/psonic/commit/0a4a0a79d319f41b8a41c3d7a414cfd2626db07b?diff=split

Even though you set the password via the constructor, I was changing it into default password. Thanks again

**Comment by ppshobi** [comment]
Let me know if you spot any more
